// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: GamePB.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
[global::ProtoBuf.ProtoContract()]
public partial class Pkg : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"head", IsRequired = true)]
    public Head Head { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"body")]
    public Body Body { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class Head : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
    public string protoName { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"seq", IsRequired = true)]
    public int Seq { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"error", IsRequired = true)]
    public Error Error { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class Body : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public ReqPing reqPing { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public RspPing rspPing { get; set; }

    [global::ProtoBuf.ProtoMember(3)]
    public ReqJsonData reqJsonData { get; set; }

    [global::ProtoBuf.ProtoMember(4)]
    public RspJsonData rspJsonData { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public enum Error
{
    [global::ProtoBuf.ProtoEnum(Name = @"no_error")]
    NoError = 0,
}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
