// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: GameSystemPB.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
[global::ProtoBuf.ProtoContract()]
public partial class ReqPing : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

}

[global::ProtoBuf.ProtoContract()]
public partial class RspPing : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

}

[global::ProtoBuf.ProtoContract()]
public partial class ReqJsonData : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"content", IsRequired = true)]
    public string Content { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class RspJsonData : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"content", IsRequired = true)]
    public string Content { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class UserData : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"uid", IsRequired = true)]
    public int Uid { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"name", IsRequired = true)]
    public string Name { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"level", IsRequired = true)]
    public int Level { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"exp", IsRequired = true)]
    public int Exp { get; set; }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
