// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: GamePB.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
[global::ProtoBuf.ProtoContract()]
public partial class Pkg : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"head", IsRequired = true)]
    public Head Head { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"body")]
    public Body Body { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class Head : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"uid", IsRequired = true)]
    public long Uid { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"cmd", IsRequired = true)]
    public Cmd Cmd { get; set; } = Cmd.Ping;

    [global::ProtoBuf.ProtoMember(3, Name = @"seq", IsRequired = true)]
    public long Seq { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"result", IsRequired = true)]
    public Result Result { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class Body : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public ReqPing reqPing { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public RspPing rspPing { get; set; }

    [global::ProtoBuf.ProtoMember(3)]
    public ReqJsonData reqJsonData { get; set; }

    [global::ProtoBuf.ProtoMember(4)]
    public RspJsonData rspJsonData { get; set; }

    [global::ProtoBuf.ProtoMember(5)]
    public ReqLogin reqLogin { get; set; }

    [global::ProtoBuf.ProtoMember(6)]
    public RspLogin rspLogin { get; set; }

    [global::ProtoBuf.ProtoMember(7)]
    public ReqMatch reqMatch { get; set; }

    [global::ProtoBuf.ProtoMember(8)]
    public RspMatch rspMatch { get; set; }

    [global::ProtoBuf.ProtoMember(10)]
    public RspKick rspKick { get; set; }

    [global::ProtoBuf.ProtoMember(11)]
    public ReqExitGame reqExitGame { get; set; }

    [global::ProtoBuf.ProtoMember(12)]
    public RspExitGame rspExitGame { get; set; }

    [global::ProtoBuf.ProtoMember(13)]
    public ReqLoadComplete reqLoadComplete { get; set; }

    [global::ProtoBuf.ProtoMember(14)]
    public RspLoadComplete rspLoadComplete { get; set; }

    [global::ProtoBuf.ProtoMember(1000)]
    public ReqEquip reqEquip { get; set; }

    [global::ProtoBuf.ProtoMember(1001)]
    public RspEquip rspEquip { get; set; }

    [global::ProtoBuf.ProtoMember(1002)]
    public ReqStartGame reqStartGame { get; set; }

    [global::ProtoBuf.ProtoMember(1003)]
    public RspStartGame rspStartGame { get; set; }

    [global::ProtoBuf.ProtoMember(1004)]
    public ReqGenMonster reqGenMonster { get; set; }

    [global::ProtoBuf.ProtoMember(1005)]
    public RspGenMonster rspGenMonster { get; set; }

    [global::ProtoBuf.ProtoMember(1006)]
    public ReqAttackMonster reqAttackMonster { get; set; }

    [global::ProtoBuf.ProtoMember(1007)]
    public RspAttackMonster rspAttackMonster { get; set; }

    [global::ProtoBuf.ProtoMember(1008)]
    public ReqSyncPosMonster reqSyncPosMonster { get; set; }

    [global::ProtoBuf.ProtoMember(1009)]
    public RspSyncPosMonster rspSyncPosMonster { get; set; }

    [global::ProtoBuf.ProtoMember(1010)]
    public ReqPlayerTick reqPlayerTick { get; set; }

    [global::ProtoBuf.ProtoMember(1011)]
    public RspPlayerTick rspPlayerTick { get; set; }

    [global::ProtoBuf.ProtoMember(1012)]
    public ReqFindTarget reqFindTarget { get; set; }

    [global::ProtoBuf.ProtoMember(1013)]
    public RspFindTarget rspFindTarget { get; set; }

    [global::ProtoBuf.ProtoMember(1014)]
    public ReqPlayerBullet reqPlayerBullet { get; set; }

    [global::ProtoBuf.ProtoMember(1015)]
    public RspPlayerBullet rspPlayerBullet { get; set; }

    [global::ProtoBuf.ProtoMember(1016)]
    public ReqPlayerRecoil reqPlayerRecoil { get; set; }

    [global::ProtoBuf.ProtoMember(1017)]
    public RspPlayerRecoil rspPlayerRecoil { get; set; }

    [global::ProtoBuf.ProtoMember(1018)]
    public ReqMonsterDash reqMonsterDash { get; set; }

    [global::ProtoBuf.ProtoMember(1019)]
    public RspMonsterDash rspMonsterDash { get; set; }

    [global::ProtoBuf.ProtoMember(1020)]
    public ReqPlayerHit reqPlayerHit { get; set; }

    [global::ProtoBuf.ProtoMember(1021)]
    public RspPlayerHit rspPlayerHit { get; set; }

    [global::ProtoBuf.ProtoMember(1022)]
    public ReqGenerateProp reqGenerateProp { get; set; }

    [global::ProtoBuf.ProtoMember(1023)]
    public RspGenerateProp rspGenerateProp { get; set; }

    [global::ProtoBuf.ProtoMember(1024)]
    public ReqGetProp reqGetProp { get; set; }

    [global::ProtoBuf.ProtoMember(1025)]
    public RspGetProp rspGetProp { get; set; }

}

[global::ProtoBuf.ProtoContract(Name = @"CMD")]
public enum Cmd
{
    Ping = 1,
    Json = 2,
    Login = 3,
    Match = 4,
    Kick = 5,
    ExitGame = 6,
    LoadComplete = 7,
    Equip = 1000,
    StartGame = 1001,
    GenMonster = 1002,
    AttackMonster = 1003,
    SyncPosMonster = 1004,
    PlayerTick = 1005,
    MonsterFindTarget = 1006,
    PlayerBullet = 1007,
    Recoil = 1008,
    MonsterDash = 1009,
    PlayerHit = 1010,
    GenerateProp = 1011,
    GetProp = 1012,
}

[global::ProtoBuf.ProtoContract()]
public enum Result
{
    Success = 0,
    HasBeenRegistered = 1,
    HasOnline = 2,
    RoomBusy = 3,
    RoomFull = 4,
}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
