// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: GamePlayPB.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
[global::ProtoBuf.ProtoContract()]
public partial class NetVector3 : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"x", IsRequired = true)]
    public float X { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"y", IsRequired = true)]
    public float Y { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"z", IsRequired = true)]
    public float Z { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class ReqEquip : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"weapon", IsRequired = true)]
    public WeaponType Weapon { get; set; } = WeaponType.ZuoLun;

    [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
    public bool isSelect { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class RspEquip : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"nickname", IsRequired = true)]
    public string Nickname { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"weapon", IsRequired = true)]
    public WeaponType Weapon { get; set; } = WeaponType.ZuoLun;

    [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
    public bool isSelect { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class ReqStartGame : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
    public bool isReady { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class RspStartGame : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"readyList")]
    public long[] readyLists { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public enum WeaponType
{
    ZuoLun = 1,
    JuJi = 2,
    HuoPao = 3,
    ShuiQiang = 4,
    DianCiPao = 5,
}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
