// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: GamePB.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
[global::ProtoBuf.ProtoContract()]
public partial class Pkg : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"head", IsRequired = true)]
    public Head Head { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"body")]
    public Body Body { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class Head : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"uid", IsRequired = true)]
    public long Uid { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"cmd", IsRequired = true)]
    public Cmd Cmd { get; set; } = Cmd.Ping;

    [global::ProtoBuf.ProtoMember(3, Name = @"seq", IsRequired = true)]
    public long Seq { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"result", IsRequired = true)]
    public Result Result { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class Body : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public ReqPing reqPing { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public RspPing rspPing { get; set; }

    [global::ProtoBuf.ProtoMember(3)]
    public ReqJsonData reqJsonData { get; set; }

    [global::ProtoBuf.ProtoMember(4)]
    public RspJsonData rspJsonData { get; set; }

    [global::ProtoBuf.ProtoMember(5)]
    public ReqLogin reqLoginData { get; set; }

    [global::ProtoBuf.ProtoMember(6)]
    public RspLogin rspLoginData { get; set; }

}

[global::ProtoBuf.ProtoContract(Name = @"CMD")]
public enum Cmd
{
    Ping = 1,
    Login = 2,
}

[global::ProtoBuf.ProtoContract()]
public enum Result
{
    Success = 0,
    HasBeenRegistered = 10001,
    HasOnline = 10002,
}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
