// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: GameMonster.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
[global::ProtoBuf.ProtoContract()]
public partial class ReqFindTarget : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"x", IsRequired = true)]
    public float X { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"y", IsRequired = true)]
    public float Y { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"z", IsRequired = true)]
    public float Z { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class RspFindTarget : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"uid", IsRequired = true)]
    public long Uid { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class NetVector3 : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"x", IsRequired = true)]
    public float X { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"y", IsRequired = true)]
    public float Y { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"z", IsRequired = true)]
    public float Z { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class ReqGenMonster : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
    public int actionId { get; set; }

    [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
    public int monsterIdx { get; set; }

    [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
    public int genCount { get; set; }

    [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
    public NetVector3 genPos { get; set; }

    [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
    public NetVector3 genRotate { get; set; }

    [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
    public int genType { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class RspGenMonster : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
    public int actionId { get; set; }

    [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
    public int monsterIdx { get; set; }

    [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
    public int genCount { get; set; }

    [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
    public NetVector3 genPos { get; set; }

    [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
    public NetVector3 genRotate { get; set; }

    [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
    public long mId { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class ReqAttackMonster : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
    public long mId { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"damage", IsRequired = true)]
    public float Damage { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class RspAttackMonster : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
    public long mId { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"damage", IsRequired = true)]
    public float Damage { get; set; }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
