// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: GameSystemPB.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
[global::ProtoBuf.ProtoContract()]
public partial class ReqPing : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"timestamp", IsRequired = true)]
    public long Timestamp { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class RspPing : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"timestamp", IsRequired = true)]
    public long Timestamp { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class ReqJsonData : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"content", IsRequired = true)]
    public string Content { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class RspJsonData : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"content", IsRequired = true)]
    public string Content { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class ReqLogin : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"nickname", IsRequired = true)]
    public string Nickname { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class RspLogin : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"nickname", IsRequired = true)]
    public string Nickname { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class ReqMatch : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
    public bool isReady { get; set; }

    [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
    public int roomId { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class MatchInfo : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
    public long uId { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"nickname", IsRequired = true)]
    public string Nickname { get; set; }

    [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
    public bool isReady { get; set; }

    [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
    public int roomOrder { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class RspMatch : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"matchInfoList")]
    public global::System.Collections.Generic.List<MatchInfo> matchInfoLists { get; } = new global::System.Collections.Generic.List<MatchInfo>();

    [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
    public int roomId { get; set; }

    [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
    public long ownerUId { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class RspKick : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

}

[global::ProtoBuf.ProtoContract()]
public partial class ReqExitGame : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

}

[global::ProtoBuf.ProtoContract()]
public partial class RspExitGame : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

}

[global::ProtoBuf.ProtoContract()]
public partial class PlayerData : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"uid", IsRequired = true)]
    public int Uid { get; set; }

    [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
    public string nickName { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class ReqLoadComplete : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

}

[global::ProtoBuf.ProtoContract()]
public partial class RspLoadComplete : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
