// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: GameMonster.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
[global::ProtoBuf.ProtoContract()]
public partial class ReqGenMonster : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
    public int actionId { get; set; }

    [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
    public int monsterIdx { get; set; }

    [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
    public int genCount { get; set; }

    [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
    public NetVector3 genPos { get; set; }

    [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
    public NetVector3 genRotate { get; set; }

    [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
    public int genType { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class RspGenMonster : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
    public int actionId { get; set; }

    [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
    public int monsterIdx { get; set; }

    [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
    public int genCount { get; set; }

    [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
    public NetVector3 genPos { get; set; }

    [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
    public NetVector3 genRotate { get; set; }

    [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
    public long mId { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class ReqAttackMonster : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
    public long mId { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"dir", IsRequired = true)]
    public NetVector3 Dir { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"dis", IsRequired = true)]
    public float Dis { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"hp", IsRequired = true)]
    public float Hp { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"sp", IsRequired = true)]
    public float Sp { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"duration", IsRequired = true)]
    public float Duration { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class RspAttackMonster : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
    public long mId { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"dir", IsRequired = true)]
    public NetVector3 Dir { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"dis", IsRequired = true)]
    public float Dis { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"hp", IsRequired = true)]
    public float Hp { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"sp", IsRequired = true)]
    public float Sp { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"duration", IsRequired = true)]
    public float Duration { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class ReqSyncPosMonsterItem : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
    public long mId { get; set; }

    [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
    public long uId { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"pos", IsRequired = true)]
    public NetVector3 Pos { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"dir", IsRequired = true)]
    public NetVector3 Dir { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"speed", IsRequired = true)]
    public float Speed { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class ReqSyncPosMonster : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"reqList")]
    public global::System.Collections.Generic.List<ReqSyncPosMonsterItem> reqLists { get; } = new global::System.Collections.Generic.List<ReqSyncPosMonsterItem>();

    [global::ProtoBuf.ProtoMember(2, Name = @"timestamp", IsRequired = true)]
    public long Timestamp { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class RspSyncPosMonsterItem : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
    public long mId { get; set; }

    [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
    public long uId { get; set; }

    [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
    public NetVector3 targetPos { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class RspSyncPosMonster : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"rspList")]
    public global::System.Collections.Generic.List<RspSyncPosMonsterItem> rspLists { get; } = new global::System.Collections.Generic.List<RspSyncPosMonsterItem>();

    [global::ProtoBuf.ProtoMember(2, Name = @"timestamp", IsRequired = true)]
    public long Timestamp { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class ReqFindTarget : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
    public long mId { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"type", IsRequired = true)]
    public MonsterNetType Type { get; set; } = MonsterNetType.Idle;

    [global::ProtoBuf.ProtoMember(3, Name = @"pos", IsRequired = true)]
    public NetVector3 Pos { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class RspFindTarget : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
    public long mId { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"uid", IsRequired = true)]
    public long Uid { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public enum MonsterNetType
{
    Idle = 1,
    Chase = 2,
    Shoot = 3,
}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
