// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: GamePlayerPB.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
[global::ProtoBuf.ProtoContract()]
public partial class ReqPlayerTick : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"position", IsRequired = true)]
    public NetVector3 Position { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class RspPlayerTickItem : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"uid", IsRequired = true)]
    public long Uid { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"position", IsRequired = true)]
    public NetVector3 Position { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class RspPlayerTick : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"itemList")]
    public global::System.Collections.Generic.List<RspPlayerTickItem> itemLists { get; } = new global::System.Collections.Generic.List<RspPlayerTickItem>();

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
