// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: GameBoss.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
[global::ProtoBuf.ProtoContract()]
public partial class ReqBossAction : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
    public int stateId { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"target", IsRequired = true)]
    public long Target { get; set; }

    [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
    public int settingIdx { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class RspBossAction : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
    public int stateId { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"target", IsRequired = true)]
    public long Target { get; set; }

    [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
    public int settingIdx { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class ReqAttackBoss : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"hp", IsRequired = true)]
    public float Hp { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class RspAttackBoss : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"hp", IsRequired = true)]
    public float Hp { get; set; }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
